services:
  neo4j:
    image: docker.io/neo4j:community
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # BOLT
    volumes:
      - $(pwd)/data:/data
      - $(pwd)/import:/var/lib/neo4j/import:ro
    environment:
      - NEO4J_PLUGINS=["graph-data-science", "apoc"]
      - NEO4J_AUTH=neo4j/CHANGEME
      # - NEO4J_server_memory_heap_initial__size=1G
      # - NEO4J_server_memory_heap_max__size=1G
      # - NEO4J_server_memory_pagecache_size=512M
